services:
  postgres:
    image: postgres
    container_name: postgress
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    container_name: pgAdmin
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  reddis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  pgadmin-data:
  redis-data:
